# Generated by Django 3.2.19 on 2023-05-24 18:13

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255, verbose_name='Имя')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=20, region=None, verbose_name='Номер клиента')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=30, verbose_name='Имя')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=20, region=None, verbose_name='Номер клиента')),
                ('speciality', models.CharField(max_length=150, verbose_name='Специальность')),
                ('photo', models.ImageField(blank=True, upload_to='', verbose_name='Фотография')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала работы')),
                ('experience', models.DurationField(blank=True, null=True, verbose_name='Стаж')),
            ],
            options={
                'verbose_name': 'Мастер',
                'verbose_name_plural': 'Мастера',
            },
        ),
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название салона')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('time_work', models.CharField(max_length=100, verbose_name='Режим работы')),
                ('photo', models.ImageField(blank=True, upload_to='', verbose_name='Фотография')),
            ],
            options={
                'verbose_name': 'Салон красоты',
                'verbose_name_plural': 'Салоны красоты',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название услуги')),
                ('price', models.PositiveIntegerField(verbose_name='Цена услуги')),
                ('photo', models.ImageField(blank=True, upload_to='', verbose_name='Фотография')),
                ('masters', models.ManyToManyField(related_name='services', to='beauty.Master', verbose_name='Мастера')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Имя')),
                ('rate', models.PositiveSmallIntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], verbose_name='Оцените от 1 до 5')),
                ('review_text', models.TextField(max_length=500, verbose_name='Отзыв')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beauty.master', verbose_name='Mастер')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата записи')),
                ('time', models.TimeField(choices=[('1', '9.00-10.00'), ('2', '10.00-11.00'), ('3', '11.00-12.00'), ('4', '12.00-13.00'), ('5', '14.00-15.00'), ('6', '15.00-16.00'), ('7', '16.00-17.00'), ('8', '17.00-18.00')], verbose_name='Время записи')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beauty.client', verbose_name='Клиент')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beauty.master', verbose_name='Мастер')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beauty.salon', verbose_name='Салон')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beauty.service', verbose_name='Услуги')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
